### ISSUE TITLE
Consider using DocFX cross-references for Json.NET

### ISSUE THREAD

**Issue by malcolmr** [nodatime/nodatime.org#13]
See comments in nodatime/nodatime#693 (using our generated `xrefmap.yml` from an external project).

We should consider using a similar pattern for _our_ dependencies; in particular, Json.NET.

**Comment by jskeet** [comment]
Filed https://github.com/JamesNK/Newtonsoft.Json/issues/2041 to request a ref map. We'll see whether it goes anywhere.
