### ISSUE TITLE
Broken link on Installation page

### ISSUE THREAD

**Issue by DanCarterGMSL** [nodatime/nodatime.org#158]
On [the Installation page](https://nodatime.org/3.1.x/userguide/installation), under "System requirements", there's a link to the .NET Standard versions documentation. This link is broken. I would provide a PR but I'm not quite sure what information that page used to contain!

**Comment by jskeet** [comment]
I'll have a look when I can - it won't be before the weekend at the earliest I'm afraid.

**Comment by DanCarterGMSL** [comment]
Thanks - I should add that this isn't blocking me on anything; I just noticed it as I was reading the docs. It could well be that https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0#net-standard-versions is the replacement for the previous link.
