### ISSUE TITLE
API documentation has incorrect "Since" versions

### ISSUE THREAD

**Issue by malcolmr** [nodatime/nodatime.org#198]
Not sure how easy this might be to fix, but I notice that the "Since" version shown on API documentation seems to only ever be one of "1.4.x", "3.1.x", or "unstable".

e.g.

- https://nodatime.org/3.2.x/api/NodaTime.Instant.html shows "Since: 1.4.x" for everything,
- https://nodatime.org/2.0.x/api/NodaTime.DateAdjusters.html (in 2.0) shows "Since: 3.1.x", and
- https://nodatime.org/3.2.x/api/NodaTime.Extensions.TimeProviderExtensions.html (or any of the methods added in 3.2.0) shows "Since: unstable".

**Comment by jskeet** [comment]
Thanks, will have a look. My guess is that it's due to docfx member IDs changing over time, but we'll see.
(If it turns out to be really hard to fix, I'll just get rid of the "Since" bit for the moment.)

**Comment by jskeet** [comment]
Looks like it's going to be *utterly* trivial: we're currently considering the versions assuming that the directory list we get is already in order - which is what happens in Windows. I just need to order them.
