### ISSUE TITLE
3.0.0-beta02, released date is not correct I think

### ISSUE THREAD

**Issue by Nothing-Works** [nodatime/nodatime.org#80]
on the [version page](https://nodatime.org/versions)
![screenshot-nodatime org-2020 05 14-16_26_06](https://user-images.githubusercontent.com/18606648/81892697-d9b5f080-95ff-11ea-9560-8b828932b392.png)

I think this is not correct, it should be 2020.

**Comment by jskeet** [comment]
Whoops, thanks, will fix.
