### ISSUE TITLE
Fix/Add documentation for 3.0

### ISSUE THREAD

**Issue by malcolmr** [nodatime/nodatime.org#84]
Now that 3.0 have been released, we need some documentation.

This means at least the following:

- [x] branch `src/NodaTime.Web/Markdown/unstable/` to `src/NodaTime.Web/Markdown/3.0.x` (which will fix https://nodatime.org/userguide/).
- [x] remove all of the `unstable/` directory except for `src/NodaTime.Web/Markdown/unstable/index.json`, which needs an updated parent.
- [x] add the generated API documentation; I _think_ this is done nowadays by updating and then running https://github.com/nodatime/nodatime.org/blob/master/build/buildhistory.sh. (This will fix https://nodatime.org/api/.)
- [x] add information about the new version to https://nodatime.org/versions. (@jskeet already has a draft for this.)
- [ ] update/follow https://nodatime.org/developer/release-process as-needed.
- [ ] update https://nodatime.org/developer/roadmap as-needed.

Plus any minor updates we run into while doing the above:
- [x] I've just run across a misplaced `localdate-patterns.md` from 67ee2e2 that should be fixed before we branch the userguide above.
- [x] https://nodatime.org/developer/website has a lot of dead links.

I'm going to take a look at the latter group; @jskeet will do the former.

**Comment by jskeet** [comment]
I'm on it.

**Comment by malcolmr** [comment]
(When branching `unstable/`, make sure to include https://github.com/nodatime/nodatime.org/commit/cc96d1a8430c2b68d9e6fa9685d17d634474836e.)

**Comment by jskeet** [comment]
Web site build is running, hopefully with 3.0 in it...

**Comment by jskeet** [comment]
Hmm. Well we've definitely published the new version, but it doesn't have the 3.0 API docs in. Investigating.

**Comment by jskeet** [comment]
Think I've got it. Pushing a PR, then will trigger the build again.

**Comment by malcolmr** [comment]
(I've added some extra tasks above, though we can handle those at leisure once the API docs are fixed.)

**Comment by jskeet** [comment]
Looks like we have working docs again :) I've kept some notes about things to update in the release docs - will edit over the weekend.

**Comment by jskeet** [comment]
Well it took rather a long time to edit the docs for releasing, but I've now done it...
