### ISSUE TITLE
API documentation doesn't document nullable reference types

### ISSUE THREAD

**Issue by malcolmr** [nodatime/nodatime.org#89]
This might be (effectively) a dupe of https://github.com/nodatime/nodatime/issues/1269, but I notice that none of the generated API documentation includes anything about nullable reference types.

Two examples:

* `ZonedDateTimePattern.WithResolver()` accepts a `ZoneLocalMappingResolver?`, but the documentation just shows it as [`ZonedDateTimePattern.WithResolver(ZoneLocalMappingResolver)`](https://nodatime.org/3.0.x/api/NodaTime.Text.ZonedDateTimePattern.html#NodaTime_Text_ZonedDateTimePattern_WithResolver_NodaTime_TimeZones_ZoneLocalMappingResolver_).
* `IDateTimeZoneProvider.GetZoneOrNull()` returns a `DateTimeZone?`, but the documentation shows it as [`DateTimeZone GetZoneOrNull(string id)`](https://nodatime.org/3.0.x/api/NodaTime.IDateTimeZoneProvider.html#NodaTime_IDateTimeZoneProvider_GetZoneOrNull_System_String_).

**Comment by jskeet** [comment]
Oh, that's annoying. I'm sure I used to have this working. Will look when I get a chance.

Ah - it may be that it's because buildhistory.sh doesn't take the extra step that we do in the normal build. That should be fairly easy to fix.

**Comment by malcolmr** [comment]
Weirdly, I notice we have two different API entries for e.g. the `Interval`constructor:

- [`Interval(Instant, Instant)`](https://nodatime.org/3.0.x/api/NodaTime.Interval.html#NodaTime_Interval__ctor_NodaTime_Instant_NodaTime_Instant_), listed as "Since 1.0.x"
- [`Interval(Nullable<Instant>, Nullable<Instant>)`](https://nodatime.org/2.0.x/api/NodaTime.Interval.html#NodaTime_Interval__ctor_System_Nullable_NodaTime_Instant__System_Nullable_NodaTime_Instant__), listed as "Since 2.0.x"

I _think_ that's correct, though the `Nullable<>` part is bizarre (it _is_ correctly shown as `Instant?` in the declaration.).

**Comment by jskeet** [comment]
Yes, that *is* correct for Interval, because we have both constructors. I don't know when docfx decides to use `Nullable<Foo>` instead of `Foo?` but I'm not overly bothered.
GetZoneOrNull is broken in the "unstable" version as well though, so I don't think it's just a matter of adding an extra step to buildhistory.

I did update docfx as part of the change yesterday, so my previous hack may need adjusting. I'll also see if there's been any progress in including it in docfx itself...

**Comment by jskeet** [comment]
Ah - our fixer doesn't actually *indicate* the NRTs, it just makes docfx work at all. I suspect it's now not required at all any more. I'll check.
But yes, we still need to actually document them properly.

**Comment by jskeet** [comment]
Right, removing the "fixer" part but let's leave this issue open. I doubt that it'll be fixed before docfx 3 unfortunately.

**Comment by malcolmr** [comment]
fwiw, I was confused by this again today, this time for https://nodatime.org/3.0.x/api/NodaTime.ZonedDateTime.html#NodaTime_ZonedDateTime_ToString_System_String_System_IFormatProvider_, which the documentation renders as

```csharp
public string ToString(string patternText, IFormatProvider formatProvider)
```

even though both parameters are nullable (https://github.com/nodatime/nodatime/blob/0052eb8/src/NodaTime/ZonedDateTime.cs#L551).

**Comment by jskeet** [comment]
Yup, it's definitely annoying. I suspect it will be fixed in docfx v3, but I'm still not expecting that *massively* soon...

**Comment by jskeet** [comment]
Looks like this is now working in the "unstable" docs. I suspect it would be quite a bit of work to regenerate the docs for 3.0 and 3.1 though. When 3.2 is released, presumably fewer people will care about 3.0 and 3.1 anyway, so I'll just close this.
